from pydantic import BaseModel, Field


class Chat_Request(BaseModel):
    message: str

class Chat_Response(BaseModel):
    response: str = Field(..., description="The response generated by the chat model")


